const i18n = {
    id: {
        loading: "Memuat...",
        titlemain: "LotusRex Servis",
        sidebtn1: "Alat & Utilitas",
        sidebtn1desc: "Kumpulan alat bantu cepat yang dapat Anda gunakan. Klik \"Gunakan Alat\" untuk membuka antarmuka masing-masing.",
        sidebtn2: "Permainan",
        sidebtn3: "Kata Kunci Stok",
        sidebtn4: "Basis Data",
        btnTool: "Gunakan Alat",
        urltab: "Perpendek URL",
        urltabdesc: "Persingkat tautan panjang Anda dengan cepat.",
        convsctab: "Konverter Script",
        convsctabdesc: "Konversi dua arah antara Bookmarklet dan JavaScript rapi.",
        svgoptimizer: "SVG Optimizer",
        svgoptimizerdesc: "Minimalkan kode SVG untuk performa web yang lebih cepat.",
        aspectratiocalculator: "Aspect Ratio Calculator",
        aspectratiocalculatordesc: "Hitung dimensi gambar/video berdasarkan rasio (misal: 16:9).",
        resolutionpresets: "Resolution Presets",
        resolutionpresetsdesc: "Lihat standar resolusi industri.",
        designgraphics: "Desain Grafis",
        designgraphicsdesc: "Kumpulan alat bantu cepat yang berhubungan dengan desain grafis.",
        toolsutilities: "Tools & Utilities",
        toolsutilitiesdesc: "Kumpulan alat bantu cepat yang dapat Anda gunakan. Klik \"Gunakan Alat\" untuk membuka antarmuka masing-masing.",
        timedrift: "Time Drift Checker",
        timedriftdesc: "Cek akurasi jam Anda terhadap waktu server online yang kredibel.",
        colorpaletteextractor: "Color Palette Extractor",
        colorpaletteextractordesc: "Ekstrak palet warna dominan dari gambar yang diunggah.",
        colorpalettegenerator: "Color Palette Generator",
        colorpalettegeneratordesc: "Buat palet harmonis (Shades, Tints, Gradient Blend).",
        primtab: "Primbon Jawa",
        primtabdesc: "Alat primbon Jawa digital untuk ramalan dan perhitungan tradisional.",
        currtab: "Kurs Mata Uang",
        currtabdesc: "Konversi nilai mata uang terkini dengan mudah.",
        qrcode: "Alat QR Code",
        qrcodedesc: "Buat dan pindai kode QR menggunakan kamera atau file gambar.",
        barcodetab: "Alat Barcode",
        barcodetabdesc: "Generator (Simulasi) dan Reader Barcode (Kamera/File).",
        cryptotab: "Alat Kriptografi & Hash",
        cryptotabdesc: "Enkripsi/Dekripsi AES, Hitung Hash File (SHA-256).",
        passwordgenerator: "Generator Kata Sandi",
        passwordgeneratordesc: "Buat kata sandi kuat dengan kriteria yang dapat disesuaikan.",
        hibpcheck: "Pemeriksa Kebocoran Kata Sandi",
        hibpcheckdesc: "Periksa apakah kata sandi Anda pernah bocor dalam pelanggaran data.",
        csvtojson: "CSV ke JSON",
        csvtojsondesc: "Konversi data CSV menjadi format JSON dengan mudah.",
        datavalidator: "Data Validator (Regex)",
        datavalidatordesc: "Uji Regular Expression (Regex) untuk validasi format data.",
        base64converter: "Konverter Base64",
        base64converterdesc: "Encode/Decode teks dan konversi file ke Base64 (Data URI).",
        timedriftchecker: "Pemeriksa Penyimpangan Waktu",
        timedriftcheckerdesc: "Periksa penyimpangan waktu sistem Anda terhadap server waktu online.",
        advanced: "Filter Lanjutan",
        noResults: "Tidak ditemukan hasil."
    },
    en: {
        loading: "Loading...",
        titlemain: "LotusRex Services",
        sidebtn1: "Tools & Utilities",
        sidebtn1desc: "A collection of quick utility tools you can use. Click 'Use Tool' to open their interfaces.",
        sidebtn2: "Games",
        sidebtn3: "Stock Keyworder",
        sidebtn4: "Database",
        btnTool: "Use Tool",
        urltab: "URL Shortener",
        urltabdesc: "Quickly shorten your long links.",
        convsctab: "Script Converter",
        convsctabdesc: "Convert between Bookmarklet and pretty JavaScript.",
        svgoptimizer: "SVG Optimizer",
        svgoptimizerdesc: "Minimize SVG code for faster web performance.",
        aspectratiocalculator: "Aspect Ratio Calculator",
        aspectratiocalculatordesc: "Calculate image/video dimensions based on ratio (e.g., 16:9).",
        resolutionpresets: "Resolution Presets",
        resolutionpresetsdesc: "View industry standard resolutions.",
        designgraphics: "Graphic Design",
        designgraphicsdesc: "A collection of quick tools related to graphic design.",
        toolsutilities: "Tools & Utilities",
        toolsutilitiesdesc: "A collection of quick utility tools you can use. Click 'Use Tool' to open their interfaces.",
        timedrift: "Time Drift Checker",
        timedriftdesc: "Check your clock's accuracy against credible online server time.",
        colorpaletteextractor: "Color Palette Extractor",
        colorpaletteextractordesc: "Extract dominant color palettes from uploaded images.",
        colorpalettegenerator: "Color Palette Generator",
        colorpalettegeneratordesc: "Create harmonious palettes (Shades, Tints, Gradient Blend).",
        primtab: "Javanese Primbon",
        primtabdesc: "Digital Javanese primbon tool for traditional predictions and calculations.",
        currtab: "Currency Converter",
        currtabdesc: "Convert currency values easily.",
        qrcode: "QR Code Tool",
        qrcodedesc: "Generate and scan QR codes using camera or image files.",
        barcodetab: "Barcode Tool",
        barcodetabdesc: "Barcode Generator (Simulation) and Reader (Camera/File).",
        cryptotab: "Cryptography & Hash Tool",
        cryptotabdesc: "AES Encrypt/Decrypt, File Hashing (SHA-256).",
        passwordgenerator: "Password Generator",
        passwordgeneratordesc: "Create strong passwords with customizable criteria.",
        hibpcheck: "Have I Been Pwned Checker",
        hibpcheckdesc: "Check if your password has been exposed in data breaches.",
        csvtojson: "CSV to JSON",
        csvtojsondesc: "Easily convert CSV data into JSON format.",
        datavalidator: "Data Validator (Regex)",
        datavalidatordesc: "Test Regular Expressions (Regex) for data format validation.",
        base64converter: "Base64 Converter",
        base64converterdesc: "Encode/Decode text and convert files to Base64 (Data URI).",
        timedriftchecker: "Time Drift Checker",
        timedriftcheckerdesc: "Check your system's time drift against online time servers.",
        advanced: "Advanced Filters",
        noResults: "No results found."
    }
};
